const fs = require('fs');
const p = (f,c) => { fs.mkdirSync(require('path').dirname(f),{recursive:true}); fs.writeFileSync(f,c,'utf8'); console.log('wrote:',f); };

p('README.md', [
'# GameGenie',
'> AI-powered gaming portal for kids - think it, create it, play it!',
'',
'## Quick Start',
'`ash',
'git clone https://github.com/kbvnkishore/GameGenie.git',
'cd GameGenie',
'npm install',
'npm start   # http://localhost:3000  (no AWS needed)',
'`',
'',
'## How It Works',
'1. Kid opens http://localhost:3000',
'2. Sees Problem of the Day and pre-selected game library',
'3. Types a game idea in the idea box',
'4. GameGenie AI generates the game and returns a play link',
'5. New game is added to the library',
'',
'## Architecture',
'`',
'Browser -> Express (server/) -> mockAgentService   (local, USE_MOCK=true)',
'                             -> bedrockAgentService (AWS,   USE_MOCK=false)',
'                                   |-- KidsGamePortal Bedrock Agent (portal UX)',
'                                   +-- GameGenie Bedrock Agent     (game brain)',
'`',
'',
'## Project Structure',
'`',
'agents/',
'  game-genie/            AI brain - generates games from ideas',
'    agent-config.json',
'    actions/action-group.json   GenerateGame, AddGameToLibrary, GetGameLibrary',
'    prompts/system-prompt.md',
'  kids-game-portal/      Website face - kid interaction',
'    agent-config.json',
'    actions/action-group.json   GetProblemOfTheDay, GetFeaturedGames, SubmitGameIdea',
'    prompts/system-prompt.md',
'server/',
'  index.js               Express entry point, port 3000',
'  routes/portal.js       API routes',
'  services/',
'    mockAgentService.js      local dev, no AWS',
'    bedrockAgentService.js   real AWS Bedrock',
'public/',
'  index.html             Kids portal UI',
'  css/portal.css         Space-themed dark design',
'  js/portal.js           Frontend logic',
'infrastructure/cloudformation/bedrock-agent.yaml',
'scripts/',
'  test-agent.js          npm test',
'  deploy.js              CloudFormation deploy',
'  agent-utils.js         update/prepare/alias/backup AWS agents',
'.env.local               USE_MOCK_AGENTS=true (default)',
'.env.dev                 dev AWS config',
'.env.prod                prod AWS config',
'`',
'',
'## API Endpoints',
'| Method | Endpoint | Description |',
'|--------|----------|-------------|',
'| GET | /api/health | Health check + current mode |',
'| GET | /api/portal/problem | Problem of the day |',
'| GET | /api/portal/games | Game library |',
'| POST | /api/portal/idea | Submit idea, returns game link |',
'',
'## Environment Variables',
'`ash',
'USE_MOCK_AGENTS=true          # true=local mock, false=real AWS Bedrock',
'AWS_REGION=us-east-1',
'GAME_GENIE_AGENT_ID=          # from AWS Bedrock console',
'GAME_GENIE_AGENT_ALIAS_ID=    # from CloudFormation output',
'KIDS_PORTAL_AGENT_ID=         # from AWS Bedrock console',
'KIDS_PORTAL_AGENT_ALIAS_ID=   # from CloudFormation output',
'`',
'',
'## Deploy to AWS',
'`ash',
'npm test                                              # validate configs',
'npm run deploy:dev                                    # deploy CloudFormation',
'# copy Agent IDs from AWS console into .env.dev',
'node scripts/agent-utils.js update AGENT_ID game-genie',
'node scripts/agent-utils.js update AGENT_ID kids-game-portal',
'NODE_ENV=dev npm start                                # test against real AWS',
'`',
'',
'## Version Control Workflow',
'`ash',
'npm test && npm start                                 # test locally',
'git add . && git commit -m "message"',
'git push origin main                                  # triggers CI/CD',
'node scripts/agent-utils.js update AGENT_ID game-genie  # sync AWS agent',
'`',
'',
'## Scripts',
'`ash',
'npm test                                    # validate all agent configs',
'npm start                                   # start server (mock mode)',
'npm run dev                                 # start with nodemon',
'npm run deploy:dev / deploy:prod            # CloudFormation deploy',
'node scripts/agent-utils.js update  ID name # update AWS agent',
'node scripts/agent-utils.js prepare ID      # prepare agent',
'node scripts/agent-utils.js alias   ID name # create version alias',
'node scripts/agent-utils.js versions ID     # list versions',
'node scripts/agent-utils.js backup  name    # backup config to S3',
'`',
'',
'## CI/CD',
'Push to main triggers GitHub Actions: npm test then deploy.',
'Required secrets: AWS_ACCESS_KEY_ID_DEV, AWS_SECRET_ACCESS_KEY_DEV,',
'AWS_ACCESS_KEY_ID_PROD, AWS_SECRET_ACCESS_KEY_PROD',
'',
'## License',
'MIT',
].join('\n'));

p('docs/ARCHITECTURE.md', [
'# Architecture',
'',
'## Two-Agent Design',
'| Agent | Role |',
'|-------|------|',
'| KidsGamePortal | Website face - problems, game list, idea collection |',
'| GameGenie | AI brain - idea processing, game generation, library management |',
'',
'## Service Layer',
'- mockAgentService.js - in-memory, no AWS, USE_MOCK_AGENTS=true',
'- bedrockAgentService.js - real Bedrock via InvokeAgentCommand streaming',
'',
'## Adding a Feature',
'1. Add action to agents/*/actions/action-group.json',
'2. Implement in both service files',
'3. Add route in server/routes/portal.js if needed',
'4. Update public/js/portal.js',
'5. npm test -> npm start -> commit -> push',
].join('\n'));

p('docs/LOCAL_DEVELOPMENT.md', [
'# Local Development',
'',
'## Run',
'`ash',
'npm install && npm start   # http://localhost:3000',
'npm run dev                # with auto-restart',
'`',
'',
'## Mock Mode (default)',
'USE_MOCK_AGENTS=true in .env.local - no AWS needed.',
'Game library is in-memory and resets on restart.',
'',
'## Switch to Real AWS',
'1. npm run deploy:dev',
'2. Copy Agent IDs into .env.dev',
'3. Set USE_MOCK_AGENTS=false',
'4. NODE_ENV=dev npm start',
'',
'## Files You Edit Most',
'| File | Purpose |',
'|------|---------|',
'| agents/game-genie/agent-config.json | GameGenie instructions |',
'| agents/kids-game-portal/agent-config.json | Portal instructions |',
'| server/services/mockAgentService.js | Mock games and problems |',
'| public/js/portal.js | Frontend behaviour |',
].join('\n'));

p('.kiro/steering/product.md', [
'# Product',
'',
'GameGenie is an AI-powered kids gaming portal (ages 5-13).',
'',
'## Core Features',
'1. Problem of the Day - daily challenge on homepage',
'2. Game Library - pre-selected games to play instantly',
'3. Idea Box - kids type an idea, AI creates a game',
'4. Kid-Created Games - appear in the library after creation',
'',
'## Principles',
'- Age-appropriate and safe at all times',
'- Simple language, encouraging tone',
'- No personal information collected',
].join('\n'));

p('.kiro/steering/tech.md', [
'# Tech Stack',
'',
'- Runtime: Node.js v24, npm v11',
'- Backend: Express 4, dotenv, cors, uuid',
'- Frontend: Vanilla HTML/CSS/JS, Google Fonts (Nunito)',
'- AWS: Bedrock Claude 3 Sonnet, CloudFormation, S3',
'- SDK: @aws-sdk/client-bedrock-agent-runtime, @aws-sdk/client-bedrock-agent',
'- Dev: nodemon',
'',
'## Commands',
'`ash',
'npm install        # install deps',
'npm start          # run server',
'npm run dev        # run with nodemon',
'npm test           # validate configs',
'npm run deploy:dev # deploy to AWS dev',
'`',
].join('\n'));

p('.kiro/steering/structure.md', [
'# Project Structure',
'',
'agents/            Bedrock agent configs (game-genie, kids-game-portal)',
'server/            Express backend',
'  routes/          API route handlers',
'  services/        mockAgentService + bedrockAgentService',
'public/            Static frontend (HTML/CSS/JS)',
'infrastructure/    CloudFormation templates',
'scripts/           test-agent.js, deploy.js, agent-utils.js',
'tests/             Jest tests',
'docs/              ARCHITECTURE.md, LOCAL_DEVELOPMENT.md',
'.env.local         local mock mode',
'.env.dev           dev AWS',
'.env.prod          prod AWS',
'',
'## Conventions',
'- Agent dirs: kebab-case',
'- JS files: camelCase',
'- Env files: .env.{environment}',
].join('\n'));

console.log('All docs written.');
